# Generated by Django 4.0.4 on 2022-06-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        # migrations.CreateModel(
        #     name='Familia',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('nombre', models.CharField(max_length=50)),
        #         ('apelido', models.CharField(max_length=50)),
        #         ('año_de_nacimiento', models.IntegerField()),
        #     ],
        # ),
    ]
